[package]
name = "json-response"
version = "0.1.0"
authors = ["shenshing <lyshenshing20@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
rocket_contrib = "0.4.2"

serde = { version = "1", features = ["derive"] }
diesel = { version = "1.4.0", features = ["postgres"] }

